config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :economists, only: [:index, :new, :create, :show]

  #
  # get '/economists', to: 'economists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/economist.rb
class Economist < ApplicationRecord

  has_many :papers
  validates_presence_of :name, :age, :city


  def paper_count
    self.papers.count
  end

  def self.average_age
    select(:age).where("age > 0").average(:age)
  end

  def self.hometowns
    distinct(:city).pluck(:city)
  end

  def self.sort_by(params)
    if params[:sort] == "name"
      order(:name)
    elsif params[:sort] == "age"
      order(:age)
    elsif params[:sort] == "city"
      order(:city)
    end
  end
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :economist

  validates_presence_of :name, :pages

  def self.total_papers
    count
  end

  def self.average_pages
    average(:pages)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/economists_controller.rb
class EconomistsController < ApplicationController

  def index
    @economists = Economist.all
    @average_age = Economist.average_age
    @total_papers = Paper.total_papers
    @average_pages = Paper.average_pages
    @hometowns = Economist.hometowns


    if params[:sort] != nil
      if params[:sort] == "name" || params[:sort] == "age" || params[:sort] == "city"
        @economists = Economist.sort_by(params)
      end
    end

    age = params[:age]
    if age != nil
      @economists = Economist.where(age: (params[:age]))
    end
  end

  def show
    @economist = Economist.find(params[:id])
  end

  def new
    @economist = Economist.new
  end

  def create
    @new_economist = Economist.create(strong_params)
    @new_economist.save
    redirect_to economists_path
  end

  private

  def strong_params
    params.require(:economist).permit(:name, :age, :city, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/economists/index.html.erb
<section class="statistics-area">

  <h1>Statistics: </h1>
  <br>
  <br>
  <h2>Average age: <%= @average_age.to_i %></h2>
  <br>
  <h2>Total Number of Papers in database: <%= @total_papers.to_i %></h2>
  <br>
  <h2>Average Number of Pages for Papers in database: <%= @average_pages.to_i %></h2>
  <br>
  <br>
  <section class="hometowns">Hometowns:
    <% @hometowns.each do |town|%>
    <%= town %>
    <% end %>
    <br>
  </section>
  <br>
  <br>
</section>
<section class="sort_field">
  <%= form_tag economists_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :sort, params[:sort] %>
      <%= submit_tag "Sort", :name => nil %>
    </p>
  <% end %>
</section>

<section class='economist-ctn'>
  <% @economists.each do |economist| %>
  <section class='economist-card'>
    <div id="economist-<%= economist.id %>">
      <br>
      <img src="<%= economist.img_url %>" alt="economist photo"></img>
      <h2>Name: <%= link_to economist.name, economist_path(economist) %></h2>
      <br>
      <br>
      <% if economist.age == 0 %>
      <p>Age: <%= "deceased" %></p>
      <% else %>
      <p>Age: <%= economist.age %></p>
      <% end %>
      <p>Hometown: <%= economist.city %></p>
      <p>Number of Papers: <%= economist.paper_count %></p>
      <h2>Economist's Papers</h2>
      <br>
      <% if economist.papers.count == 0 %>
        <br>
        <p>This economist has no papers in the database</p>
      <% else %>
        <% economist.papers.each do |paper| %>
        <div id="economist-papers-<%= paper.id %>">
          <br>
          <p>Name: <%= paper.name %></p>
          <p>Pages: <%= paper.pages %></p>
          <br>
      <% end %>
          <br>
        </div>
      <% end %>
      <br>
      <br>
    </div>
  </section>
  <% end %>
</section>

app/views/economists/new.html.erb
<section="new-economist-form">
  <%= form_for(@economist) do |f| %>
  <ul>
    <li><%= f.label :name %></li>
    <li><%= f.text_field :name %></li>
    <br>
    <br>
    <li><%= f.label :age %></li>
    <li><%= f.number_field :age %></li>
    <br>
    <br>
    <li><%= f.label :city %></li>
    <li><%= f.text_field :city %></li>
    <br>
    <br>
    <li><%= f.label :image_url %></li>
    <li><%= f.text_field :img_url%></li>
    <br>
    <br>
    <li><%= f.submit :Create%></li>
  </ul>
  <% end %>
</section>

app/views/economists/show.html.erb
<section class='economist-ctn'>
  <section class='economist-card'>
    <div id="economist-<%= @economist.id %>">
      <br>
      <img src="<%= @economist.img_url %>" alt="economist photo"></img>
      <h2>Name: <%= @economist.name %></h2>
      <br>
      <br>
      <% if @economist.age == 0 %>
      <p>Age: <%= "deceased" %></p>
      <% else %>
      <p>Age: <%= @economist.age %></p>
      <% end %>
      <p>Hometown: <%= @economist.city %></p>
      <p>Number of Papers: <%= @economist.paper_count %></p>
      <h2>Economist's Papers</h2>
      <br>
      <% if @economist.papers.count == 0 %>
        <br>
        <p>This economist has no papers in the database</p>
      <% else %>
        <% @economist.papers.each do |paper| %>
        <div id="economist-papers-<%= paper.id %>">
          <br>
          <p>Name: <%= paper.name %></p>
          <p>Pages: <%= paper.pages %></p>
          <br>
      <% end %>
          <br>
        </div>
      <% end %>
      <br>
      <br>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Economists For You</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chonburi" rel="stylesheet">
  </head>

  <body>
    <div class="title">Just an Economist Page</div>
    <header>
      <ul class="top-nav">
        <%= link_to 'Economists', economists_path %>
        <%= link_to 'New Economist', new_economist_path %>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>